### ISSUE TITLE
Editors not showing in 2.3.4 with Chrome 

### ISSUE THREAD

**Issue by aivarannamaa** [jcrodriguez-dis/moodle-mod_vpl#41]
VPL 2.3.4 on Moodle 2.7 doesn't show the editors for existing submission when viewed with Windows Chrome Version "55.0.2883.87 m", but gives following JavaScript error:

```
jquery-ui-1.10.3.custom.js:6 Uncaught TypeError: Cannot read property 'className' of undefined
    at t.(anonymous function).(anonymous function)._toggleComplete (http://localhost/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:63096)
    at t.(anonymous function).(anonymous function)._toggleComplete (http://localhost/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:5029)
    at HTMLDivElement.v (http://localhost/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:62398)
    at HTMLDivElement.opt.complete (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:9285:12)
    at fire (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:1037:30)
    at Object.fireWith [as resolveWith] (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:1148:7)
    at Object.stop (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:8771:15)
    at HTMLDivElement.<anonymous> (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:9172:27)
    at Function.each (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:648:23)
    at init.each (http://localhost/mod/vpl/editor/jquery/jquery-1.9.1.js:270:17)
```
With Firefox the same task can be viewed without problems.

**Comment by aivarannamaa** [comment]
Our Moodle admin found a workaround -- in editor_utility.php replace 

```
        <div id="vpl_results" class="vpl_ide_results">
            <div id="vpl_results_accordion"></div>
        </div>
```

with 

```
        <div id="vpl_results" class="vpl_ide_results">
            <div id="vpl_results_accordion"><span></span></div>
        </div>
```

because it looks like Accordion can't handle empty tag (`_toggleComplete` gets executed before loading the content and fails because of 0 content length)

**Comment by aivarannamaa** [comment]
... but this workaround doesn't seem to work perfectly. In one test server it made editors appear and error message dissapear, but in another server it only made editors appear but error message remained.

**Comment by t6nis** [comment]
I tested it and when the error first appears and you click "Execution" then the "Comments" accordion section wont close at first click. After you click again Comments then suddenly Execution hides and the accordion starts working properly.  
For me it seems to be related with default accordion html markup. Maybe <div id="vpl_results_accordion"><h4></h4><div></div></div> would be more proper default markup for accordion than <span></span>. Afterwards Javascript will anyway populate with correct dom markup.

**Comment by jcrodriguez-dis** [comment]
Hello,
I have not been able reproduce the problem with the following configuration:
* Google Chrome Versión 55.0.2883.87 m
* Moodle 2.7.2+
* VPL 3.2.4

Is there some other config setting that I am missing?
May be something related with the theme used?

Best regards,
Juan Carlos

**Comment by aivarannamaa** [comment]
I was able to replicate the problem in VPL Demo server with following task: http://demovpl.dis.ulpgc.es/moodle/mod/vpl/forms/edit.php?id=398

If you log in with _teacher1_ then you should see the exact state I left there. 

In my computer, when I open this page with latest Windows Chrome, I get following error on JavaScript Developer console:

```
jquery-ui-1.10.3.custom.js:6 Uncaught TypeError: Cannot read property 'className' of undefined
    at t.(anonymous function).(anonymous function)._toggleComplete (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:63096)
    at t.(anonymous function).(anonymous function)._toggleComplete (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:5029)
    at HTMLDivElement.v (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-ui-1.10.3.custom.js:6:62398)
    at HTMLDivElement.opt.complete (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-1.9.1.js:9285:12)
    at fire (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-1.9.1.js:1037:30)
    at Object.fireWith [as resolveWith] (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-1.9.1.js:1148:7)
    at tick (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-1.9.1.js:8736:14)
    at jQuery.fx.tick (http://demovpl.dis.ulpgc.es/moodle/mod/vpl/editor/jquery/jquery-1.9.1.js:9317:9)
```

The difference from our server tests is that in the demo moodle the editor tabs are appearing despite of the error message.

**Comment by aivarannamaa** [comment]
I just tested that page with Chrome on Mac and got the same error.

**Comment by aivarannamaa** [comment]
I did not see the error on demo server until I evaluated my solution, got the box with proposed grade and then reloaded the page.

**Comment by jcrodriguez-dis** [comment]
Gracias Aivar por tu ayuda,
El problema parece estar relacionado con una condición de carrera en la animación de acordeón, y la solución fácil es eliminar la animación con {..animate: false} en la creación de acordeón.
He desarrollado una mejor solución para V3.3 y voy a backport a la V3.2.4 esta tarde.
Atentamente,
Juan Carlos.

**Comment by aivarannamaa** [comment]
Gracias, Juan Carlos!

( Your message encouraged me to brush up my Spanish again. I thought I had forgotten everything :) )

**Comment by jcrodriguez-dis** [comment]
Thanks Aivar for your help,
The problem was related to the accordion animation. The solution was to recreate the accordion for every evaluation. It seams that reuse the accordion generate de animation problem. I have also remove the send of the last evaluation with the load of the page. This information is taken with the files to edit.
The new code is in the  v3.2.4 in github.

Best regards,
Juan Carlos.

**Comment by jcrodriguez-dis** [comment]
Hello Aivar,
Did the official VPL 3.2.4 solve the load problem?
If it is OK, please, close the issue.

**Comment by aivarannamaa** [comment]
Looks like it's fixed now, thanks!
